<a href="https://colab.research.google.com/github/dzikrirzzn/Implementasi-Sistem-Persamaan-Linear/blob/main/Implementasi%20Sistem%20Persamaan%20Linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Metode Matriks Balikan**

In [ ]:
import numpy as np

def inverse_matrix_method(A):
    """
    Compute the inverse of a square matrix A using NumPy.

    Parameters:
    A : numpy.ndarray
        The square matrix.

    Returns:
    numpy.ndarray or None
        The inverse of the matrix A if it exists, None otherwise.
    """
    # Check if A is square
    if A.shape[0] != A.shape[1]:
        print("Error: Input matrix is not square.")
        return None

    # Compute the determinant
    det = np.linalg.det(A)

    # Check if the determinant is zero (non-invertible matrix)
    if np.isclose(det, 0):
        print("Error: Matrix is singular (non-invertible).")
        return None

    # Compute the inverse
    A_inv = np.linalg.inv(A)

    return A_inv

# Example usage:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

A_inv = inverse_matrix_method(A)
if A_inv is not None:
    print("Inverse of A:")
    print(A_inv)


Inverse of A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


### **Metode Dekomposisi LU Gauss**


In [ ]:
import numpy as np

def lu_decomposition_gauss(A):
    """
    Perform LU decomposition of a square matrix A using Gaussian elimination.

    Parameters:
    A : numpy.ndarray
        The square matrix.

    Returns:
    L : numpy.ndarray
        Lower triangular matrix of the LU decomposition.
    U : numpy.ndarray
        Upper triangular matrix of the LU decomposition.
    """
    n = A.shape[0]
    # Initialize L as an identity matrix and U as a copy of A
    L = np.eye(n)
    U = A.astype(float)  # Convert to float

    for k in range(n-1):  # Forward elimination
        for i in range(k+1, n):
            factor = U[i, k] / U[k, k]
            L[i, k] = factor
            U[i, k:] -= factor * U[k, k:]

    return L, U

# Example usage:
A = np.array([[2, -1,  0],
              [-1,  2, -1],
              [0, -1,  2]])

L, U = lu_decomposition_gauss(A)
print("L:")
print(L)
print("U:")
print(U)

L:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
U:
[[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]


### **Metode Dekomposisi Crout**

In [ ]:
import numpy as np

def lu_decomposition_crout(A):
    """
    Perform LU decomposition of a square matrix A using Crout's method.

    Parameters:
    A : numpy.ndarray
        The square matrix.

    Returns:
    L : numpy.ndarray
        Lower triangular matrix of the LU decomposition.
    U : numpy.ndarray
        Upper triangular matrix of the LU decomposition.
    """
    n = A.shape[0]
    L = np.zeros((n, n))
    U = np.zeros((n, n))

    for j in range(n):
        L[j, j] = 1  # Set diagonal of L to 1
        for i in range(j, n):
            U[j, i] = A[j, i] - np.dot(L[j, :j], U[:j, i])
        for i in range(j+1, n):
            L[i, j] = (A[i, j] - np.dot(L[i, :j], U[:j, j])) / U[j, j]

    return L, U

# Example usage:
A = np.array([[2, -1,  0],
              [-1,  2, -1],
              [0, -1,  2]])

L, U = lu_decomposition_crout(A)
print("L:")
print(L)
print("U:")
print(U)


L:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.         -0.66666667  1.        ]]
U:
[[ 2.         -1.          0.        ]
 [ 0.          1.5        -1.        ]
 [ 0.          0.          1.33333333]]
